config/routes.rb
CMS::Application.routes.draw do
  resources :uploads

  resources :file_uploaders

  get "home/index"

  resources :pages

  get "newFile" => "uploads#new", :as => "newFile"
  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"
  root :to => "sessions#new"
  resources :users
  resources :sessions
  get "secret" => "secret#index"

  root :to => 'home#index'
  get 'css/*resource' => "uploads#show"
  get '*page' => "pages#show" 

end

app/models/page.rb
class Page < ActiveRecord::Base
	attr_accessible :name, :content, :slug

  	validates_presence_of :name, :content
end

app/models/upload.rb
class Upload < ActiveRecord::Base
	attr_accessible :gallery_id, :name, :image, :remote_image_url
 	belongs_to :gallery
  	mount_uploader :image, ImageUploader

  	def image?
  		['png','jpg','gif'].include? image.file.extension
  	end

  	def script?
  		!image?
  	end
end

app/models/user.rb
class User < ActiveRecord::Base
	attr_accessible :email, :password, :password_confirmation
  	has_secure_password
  	validates_presence_of :password, :on => :create
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery
	force_ssl

	before_filter :require_auth

	private

	def current_user
	@current_user ||= User.find(session[:user_id]) if session[:user_id]
	end
	helper_method :current_user

	def require_auth
		redirect_to login_path, notice: "Not authorized, Please log in first" unless current_user
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  # GET /pages
  # GET /pages.json
  def index
    @pages = Page.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @pages }
    end
  end

  # GET /pages/1
  # GET /pages/1.json
  def show
    @page = Page.find_by_slug(params[:page])

    render text: @page.content
  end

  # GET /pages/new
  # GET /pages/new.json
  def new
    @page = Page.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @page }
    end
  end

  # GET /pages/1/edit
  def edit
    @page = Page.find(params[:id])
  end

  # POST /pages
  # POST /pages.json
  def create
    @page = Page.new(params[:page])

    respond_to do |format|
      if @page.save
        format.html { redirect_to pages_path, notice: 'Page was successfully created.' }
        format.json { render json: @page, status: :created, location: @page }
      else
        format.html { render action: "new" }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /pages/1
  # PUT /pages/1.json
  def update
    @page = Page.find(params[:id])

    respond_to do |format|
      if @page.update_attributes(params[:page])
        format.html { redirect_to pages_path, notice: 'Page was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pages/1
  # DELETE /pages/1.json
  def destroy
    @page = Page.find(params[:id])
    @page.destroy

    respond_to do |format|
      format.html { redirect_to pages_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/secret_controller.rb
class SecretController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_filter :require_auth
  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to pages_path, :notice => "Logged in!"
    else
      flash.now.alert = "Invalid email or password"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "Logged out!"
  end
end

app/controllers/uploads_controller.rb
class UploadsController < ApplicationController
  # GET /uploads
  # GET /uploads.json
  def index
    @uploads = Upload.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @uploads }
    end
  end

  # GET /uploads/1
  # GET /uploads/1.json
  def show
    @upload = Upload.find(params[:id])

    if @upload.image?
      render :show_image
    else
      render :show_script
    end
  end

  # GET /uploads/new
  # GET /uploads/new.json
  def new
    @upload = Upload.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @upload }
    end
  end

  # GET /uploads/1/edit
  def edit
    @upload = Upload.find(params[:id])
    File.open(@upload.image.file.path) do |f|
      @content = f.read()
    end

    modes = {'html'=> 'html', 'css'=> 'css', 'js'=> 'javascript'}
    @mode = modes[@upload.image.file.extension]

    if @upload.image?
      render :edit_image
    else
      render :edit_script
    end
  end

  # POST /uploads
  # POST /uploads.json
  def create
    @upload = Upload.new(params[:upload])

    respond_to do |format|
      if @upload.save
        format.html { redirect_to @upload, notice: 'Upload was successfully created.' }
        format.json { render json: @upload, status: :created, location: @upload }
      else
        format.html { render action: "new" }
        format.json { render json: @upload.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /uploads/1
  # PUT /uploads/1.json
  def update
    @upload = Upload.find(params[:id])

    respond_to do |format|
      if @upload.update_attributes(params[:upload])
        format.html { redirect_to @upload, notice: 'Upload was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @upload.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /uploads/1
  # DELETE /uploads/1.json
  def destroy
    @upload = Upload.find(params[:id])
    @upload.destroy

    respond_to do |format|
      format.html { redirect_to uploads_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_filter :require_auth
  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      redirect_to root_url, :notice => "Signed up!"
    else
      render "new"
    end
  end
end

app/helpers/file_uploaders_helper.rb
module FileUploadersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/uploads_helper.rb
module UploadsHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<%= link_to "Editor", pages_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html style="background-color:#222">
<head>
  <title>CMS</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body style="background:#222;">
	  <div id="main-nav-holder">
  <nav id="main-nav">
    <ul>
      <li>
            <%= link_to "Pages", pages_path, id: 'pages', class: current_page?(pages_path) ? 'current' : '' %>
      </li>
      
            <li>
              <%= link_to "New page", new_page_path, id: 'new_page', class: current_page?(new_page_path) ? 'current' : ''%>
            </li>
            <li>
              <%= link_to "Uploaded files", uploads_path, id: 'new_file', class: current_page?(uploads_path) ? 'current' : ''%>
            </li>
            <li>
              <%= link_to "Upload file", newFile_path, id: 'new_file', class: current_page?(newFile_path) ? 'current' : ''%>
            </li>
            <li>
              <%= link_to "Sign up", signup_path, id: 'sign_up', class: current_page?(signup_path) ? 'current' : ''%>
            </li>
    </ul>
  </nav>
</div>
<div id:="page" style="background-color: #222; height:100%;"><%= yield %>


</body>
</html>

app/views/pages/_form.html.erb
<style type="text/css" media="screen">
  #editor { 
    position: absolute;
    top: 0;
    right: 0;
    bottom: 0;
    left: 0;
  }
</style>


<%= form_for(@page) do |f| %>
  <% if @page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@page.errors.count, "error") %> prohibited this page from being saved:</h2>
      <div style="position:relative; width:100%, height:300px">
        <ul>
          <% @page.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label 'Custom URL' %>
  <%= f.text_field :slug %>


  <div style="position:relative; width:100%; height:300px">
    <%= f.text_area :content, id:"editor_text" %>
    <div id="editor" style="padding-top:15px;"></div>
  </div>
 
  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/pages/edit.html.erb
<div id="Editor">
<h1 style="padding-bottom:20px;">Editing page</h1>

<%= render 'form' %>

<%= link_to 'Show', @page %> |
<%= link_to 'Back', pages_path %>
</div>

app/views/pages/index.html.erb
<div id="content">
  
<h1 style="padding-bottom:20px;">Listing pages</h1>

<table>
  <tr>
    <th style="padding-bottom:10px;">Name</th>
    <th style="padding-bottom:10px;">Content</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @pages.each do |page| %>
  <tr>
    <td style="padding-right:10px;"><%= page.name %></td>
    <td><%= page.content %></td>
    <td style="padding-left:25px;"><%= link_to 'Show', page %></td>
    <td><%= link_to 'Edit', edit_page_path(page) %></td>
    <td><%= link_to 'Destroy', page, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Page', new_page_path %>
<div id="logout" style="float:right; padding-right:20px;">
<%= link_to 'Logout', logout_path %>
</div>
</div>

app/views/pages/new.html.erb
<div id="Editor">
<h1 style="padding-bottom:20px;">New page</h1>

<%= render 'form' %>

<%= link_to 'Back', pages_path %>
<div id="logout" style="float:right; padding-right:20px;">
<%= link_to 'Logout', logout_path %>
</div>
</div>

app/views/pages/show.html.erb
<div id="content">
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @page.name %>
</p>

<p>
  <b>Content:</b>
  <%= @page.content %>
</p>


<%= link_to 'Edit', edit_page_path(@page) %> |
<%= link_to 'Back', pages_path %>
<div id="logout" style="float:right; padding-right:20px; padding-top:90px;">
<%= link_to 'Logout', logout_path %>
</div>
</div>

app/views/secret/index.html.erb
<%= image_tag "gandalf.jpg" %>
<p>Is it secret? Is it safe?</p>

app/views/uploads/_form.html.erb
<%= form_for @upload, :html => {:multipart => true} do |f| %>
  <% if @upload.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@upload.errors.count, "error") %> prohibited this upload from being saved:</h2>

      <ul>
      <% @upload.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.file_field :image %>
    <%= f.submit %>
  </div>
<% end %>

app/views/uploads/edit.html.erb
<div id="content">
<h1 style="padding-bottom:20px;">Editing upload</h1>

<%= render 'form' %>

<%= link_to 'Show', @upload %> |
<%= link_to 'Back', uploads_path %>
<div id="logout" style="float:right; padding-right:20px;">
<%= link_to 'Logout', logout_path %>
</div>
</div>

app/views/uploads/edit_image.html.erb
<div id="Editor">
<h1 style="padding-bottom:20px;">Editing upload</h1>

<%= render 'form' %>

<%= link_to 'Show', @upload %> |
<%= link_to 'Back', uploads_path %>
</div>

app/views/uploads/edit_script.html.erb
<div id="Editor">
<h1 style="padding-bottom:20px;">Editing upload</h1>
<style type="text/css" media="screen">
  #editor { 
    position: absolute;
    top: 0;
    right: 0;
    bottom: 0;
    left: 0;
  }
</style>


<%= form_for(@upload) do |f| %>



  <div style="position:relative; width:100%; height:300px">
    <%= text_area_tag 'content', @content, id:"editor_text", data: {mode: @mode} %>
    <div id="editor" style="padding-top:15px;"></div>
  </div>
 
  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>
<%= link_to 'Show', @upload %> |
<%= link_to 'Back', uploads_path %>
</div>

app/views/uploads/index.html.erb
<div id="content">
<h1 style="padding-bottom:20px;">Listing file uploads</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @uploads.each do |upload| %>
  <tr>
    <td><%= upload.image %></td>
    <td><%= link_to 'Show', upload %></td>
    <td><%= link_to 'Edit', edit_upload_path(upload) %></td>
    <td><%= link_to 'Destroy', upload, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Upload', new_upload_path %>
<div id="logout" style="float:right; padding-right:20px;">
<%= link_to 'Logout', logout_path %>
</div>
</div>

app/views/uploads/new.html.erb
<div id="content">
<h1 style="padding-bottom:20px;">New file upload</h1>

<%= render 'form' %>

<%= link_to 'Back', uploads_path %>
<div id="logout" style="float:right; padding-right:20px;">
<%= link_to 'Logout', logout_path %>
</div>
</div>

app/views/uploads/show.html.erb
<div id="content">
	<h1 style="padding-bottom:20px;">Upload</h1>
	<p id="notice"><%= notice %></p>

	<%= image_tag @upload.image %>

	<%= link_to 'Edit', edit_upload_path(@upload) %> |
	<%= link_to 'Back', uploads_path %>
	<div id="logout" style="float:right; padding-right:20px;">
		<%= link_to 'Logout', logout_path %>
	</div>
</div>

app/views/uploads/show_image.html.erb
<div id="content">
	<h1 style="padding-bottom:20px;">Upload</h1>
	<p id="notice"><%= notice %></p>

	<%= image_tag @upload.image %>

</br>
	<%= link_to 'Edit', edit_upload_path(@upload) %> |
	<%= link_to 'Back', uploads_path %>
	<div id="logout" style="float:right; padding-right:20px;">
		<%= link_to 'Logout', logout_path %>
	</div>
</div>

app/views/uploads/show_script.html.erb
<div id="content">
	<h1 style="padding-bottom:20px;">Upload</h1>
	<p id="notice"><%= notice %></p>


	<%= link_to 'Edit', edit_upload_path(@upload) %> |
	<%= link_to 'Back', uploads_path %>
	<div id="logout" style="float:right; padding-right:20px;">
		<%= link_to 'Logout', logout_path %>
	</div>
</div>

app/views/users/new.html.erb
<div id="content">
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions"><%= f.submit %></div>
<% end %>
<%= link_to 'Already have an account? Click here.', login_path %>
</div>